export const MASTER_WALLET_KEY = 'ALL_WALLETS';

export const ETH_WALLET_KEY = 'ETHEREUM';
export const BSC_WALLET_KEY = 'BSC';

export const ACTIVATED_TOKEN_WALLET_LIST = [ETH_WALLET_KEY, BSC_WALLET_KEY]


export const LATEST_EXTERNAL_DATABASE_REF_ID = 'LATEST_EXTERNAL_DATABASE_REF_ID';
