export const MASTER_WALLET_KEY = 'ALL_WALLETS';

export const ETH_WALLET_KEY = 'Ethereum';
export const BSC_WALLET_KEY = 'Bsc';
export const SOL_WALLET_KEY = 'Solana'

export const ACTIVATED_TOKEN_WALLET_LIST = [ETH_WALLET_KEY, BSC_WALLET_KEY, SOL_WALLET_KEY]


export const LATEST_EXTERNAL_DATABASE_REF_ID = 'LATEST_EXTERNAL_DATABASE_REF_ID';
