export const HOME = 'HOME'

//for AppNavigator
export const AUTH_NAVIGATOR = "AUTH_NAVIGATOR"
export const DASHBOARD_NAVIGATOR = "DASHBOARD_NAVIGATOR"

//wallet creation flow
export const CREATE_WALLET_FLOW = 'CREATE_WALLET_FLOW'
export const CREATE_WALLET_MAIN = 'CREATE_WALLET_MAIN'
export const CREATE_WALLET_DETAILS = 'CREATE_WALLET_DETAILS'

//token wallet dashboard
export const WALLET_NAVIGATOR = 'WALLET_NAVIGATOR'
export const VIEW_WALLET_DASHBOARD = 'VIEW_WALLET_DASHBOARD'
export const TRANSFER_TOKEN_SCREEN = 'TRANSFER_TOKEN_SCREEN'